#204 Added admin user intialization for dev profile
code4romania/expert-consultation-api pull request #205
Opened 2020-12-11 13:52 UTC by nicolaes

### What does it fix?
Creates a default admin:admin user for local development, when no other users exist.

Closes #204 

### How has it been tested?

Tested on local environment when:
- no users existed
- there was one other user present

2020-12-11 19:06 UTC, vborcea commented on src/main/java/com/code4ro/legalconsultation/authentication/config/AuthConfiguration.java
> +        final User savedUser = userService.saveEntity(user);
if you decide to add final on local variables you shoud be consistend and add them every where

2020-12-11 20:30 UTC, nicolaes commented on src/main/java/com/code4ro/legalconsultation/authentication/config/AuthConfiguration.java
> +        final User savedUser = userService.saveEntity(user);
Good point. Removed `final` since adding it everywhere would have made code hard to read.

2020-12-14 08:34 UTC, georgebejan requested changes

2020-12-14 08:34 UTC, georgebejan commented on src/test/java/com/code4ro/legalconsultation/user/controller/UserControllerIntegrationTest.java
> +                .andDo(mvcResult -> System.out.println(mvcResult.getResponse().getContentAsString()))
please remove this

2020-12-14 08:55 UTC, nicolaes commented on src/test/java/com/code4ro/legalconsultation/user/controller/UserControllerIntegrationTest.java
> +                .andDo(mvcResult -> System.out.println(mvcResult.getResponse().getContentAsString()))
fixed

2020-12-14 10:02 UTC, georgebejan approved these changes

2020-12-14 10:03 UTC, merged